### ISSUE TITLE
No option to restart, shutdown PC, change DE on this theme

### ISSUE THREAD

**Issue by prateekmedia** [cutefishos/sddm-theme#3]
As title says, No restart, shutdown or switching the desktop environment is their which makes this theme practically unusable so please fix it.

**Comment by reionwong** [comment]
Isn’t it in the lower right corner?

**Comment by prateekmedia** [comment]
@reionwong This is the screenshot:

![](https://github.com/cutefishos/sddm-theme/raw/main/screenshot.png)

I can't find any button whatsoever regarding this.

**Comment by prateekmedia** [comment]
Oh, I had a 4k monitor and it was so tiny and not noticeable at the lower-right corner.
